services:
  db:
    image: postgres:15-alpine # Changed to Postgres to match Render
    restart: unless-stopped
    container_name: postgresdb
    environment:
      - POSTGRES_USER=inventoryiq_db_user
      - POSTGRES_PASSWORD=YtPI4Ryfn8Mp20WvbFRZnP08LiQ2kVwA
      - POSTGRES_DB=inventoryiq_db
    networks:
      - inventoryiq-network

  inventoryiq-backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: inventoryiq-be-docker:latest
    container_name: inventoryiq-be-container
    volumes:
      - ./server:/usr/src/app
      - inventoryiq_server_vendor:/usr/src/app/vendor
      - inventoryiq_server_node_modules:/usr/src/app/node_modules
    restart: unless-stopped
    ports:
       - "8000:8000"
    depends_on:
       - db
    environment:
      APP_ENV: local
      APP_KEY: "base64:g8zY2JqWjg7BOhurFZmg9v22GAKth7qJ4uJC0ACv/dU="
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: inventoryiq_db
      DB_USERNAME: inventoryiq_db_user
      DB_PASSWORD: YtPI4Ryfn8Mp20WvbFRZnP08LiQ2kVwA
    networks:
       - inventoryiq-network

  inventoryiq-frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        # IMPORTANT: For Render, change these in the Dashboard to your .onrender.com URLs
        REACT_APP_API_BASE_URL: http://localhost:8000/api
        REACT_APP_API_BASE_IMG_URL: http://localhost:8000
        REACT_APP_SECRET_KEY: "your-random-secret-key-here"
    image: inventoryiq-fe-docker:latest
    environment:
      - PORT=3000
    container_name: inventoryiq-fe-container
    restart: unless-stopped
    ports:
     - "3000:3000"
    depends_on:
      - inventoryiq-backend
    networks:
       - inventoryiq-network

volumes:
  inventoryiq_server_vendor:
  inventoryiq_server_node_modules:

networks:
  inventoryiq-network:
    driver: bridge
